### ISSUE TITLE
Release new version to maven central?

### ISSUE THREAD

**Issue by gphat** [indeedeng/java-dogstatsd-client#11]
Hello!

Looks like there are some pending changes in master, specifically the switch from `int` to `long` that didn't get released. Can we get a new release of 2.0.9? I'd love to use it for [an issue I'm working on for metrics-datadog](https://github.com/coursera/metrics-datadog/pull/23#issuecomment-68785240).

Thanks!

**Comment by gphat** [comment]
friendly ping!

**Comment by ovesh** [comment]
ack! I'll try to get it done this week.

**Comment by gphat** [comment]
Cool! Sorry to bug, glad to hear that you're on it. Thanks!

**Comment by chriscolon** [comment]
This should now be pushed out, sorry for the wait!

**Comment by gphat** [comment]
Excellent! Thanks @chriscolon! No worries about the delay, it's been that time of year. :)
