### ISSUE TITLE
Increment counter with more than 1

### ISSUE THREAD

**Issue by larsga** [indeedeng/java-dogstatsd-client#22]
I want to count the records I've written to Kinesis successfully and unsuccessfully, but I write them as batches, so I send the request, then I'm told that x succeeded and y failed. Usually, x = 20 and y = 0.

Right now I have this Scala code:

```
    val resp = kinesis.putRecords(req)

    // count successful and failed records
    for (ix <- 0 until resp.getFailedRecordCount())
      datadog.increment("kinesis.record-fail")
    for (ix <- resp.getFailedRecordCount() until events.size)
      datadog.increment("kinesis.record-written")
```

It would obviously be much more efficient to be able to write it like so:

```
    val resp = kinesis.putRecords(req)

    // count successful and failed records
    datadog.increment("kinesis.record-fail", resp.getFailedRecordCount())
    datadog.increment("kinesis.record-written", (events.size - resp.getFailedRecordCount())
```

This is not just shorter, but it also means less Datadog traffic and fewer events for the Datadog agent to process, and so on. For a service that's under high load this actually makes a difference.

**Comment by ovesh** [comment]
`increment(String aspect, String... tags)` is the same as calling  `count(aspect, 1, tags)`.
In other words, can't you call `datadog.count("kinesis.record-written", (events.size - resp.getFailedRecordCount()))` ?

**Comment by larsga** [comment]
Apologies. This is just me being really dumb.

You may want to add a `.count()` example to the README, though.
