### ISSUE TITLE
Rename com.timgroup package

### ISSUE THREAD

**Issue by scravy** [indeedeng/java-dogstatsd-client#28]
This library is effectively repackaging the library it was forked from. This causes classpath loading issues.

If you have a library that depends on the forked library and another one which depends on this, you end up with two classes with the same name with possibly different binary interfaces (e.g. in the `count` method on `NonBlockingStatsDClient`).

Please never ever do something foolish as this. Just properly rename that package.

**Comment by ovesh** [comment]
why would anybody depend on both libraries?

**Comment by scravy** [comment]
Transitive dependencies. If A depends on B which depends on the original statsd and A depends on C which depends on dogstatsd you end up having two dependencies on your classpath exporting the same package.

**Comment by ovesh** [comment]
I don't know how common the scenario you described is. If I changed the package name, I would be breaking backwards compatibility.
Also, I don't think that every time someone forks a java repo they also change the package name. I'll ask a few colleagues and come back to you with a more definite answer.

**Comment by ovesh** [comment]
I agree with aranbk's answer [here](https://github.com/arnabk/java-dogstatsd-client/issues/2).  Closing this.
