### ISSUE TITLE
NonBlockingStatsDClient is not thread-safe

### ISSUE THREAD

**Issue by ghost** [indeedeng/java-dogstatsd-client#4]
The class `NonBlockingStatsDClient` is not thread-safe (and presumably it should be). The reason for this is that a static `NumberFormat` instance is shared among all threads, but this class itself is not thread-safe. See the "synchronization" section of the `NumberFormat` docs:

http://docs.oracle.com/javase/6/docs/api/java/text/NumberFormat.html

To fix this problem, either create a new NumberFormat for each call, or create one per thread, using a `ThreadLocal<NumberFormat>`

http://stackoverflow.com/questions/1285279/java-synchronization-issue-with-numberformat

**Comment by krishna81m** [comment]
Just to confirm, do you expect us to write threadlocal implementations to return the same StatsDClient per thread and cleanup/remove() after request is processed or it is already done internally?

**Comment by domurtag** [comment]
@krishna81m AFAIK this class is thread-safe, so you can share instances of it among threads

**Comment by krishna81m** [comment]
Thanks, then, should we use thread local to get any performance benefits just in case there is any synchronization?

**Comment by domurtag** [comment]
How would using a thread local give you performance benefits?
